### ISSUE TITLE
how to extract a file from vmdk with go?

### ISSUE THREAD

**Issue by stream1990** [masahiro331/go-vmdk-parser#5]
how to extract a file from vmdk with go?
thankyou

**Comment by masahiro331** [comment]
What does it mean?
Is there a partition layer such as MasterBootRecord in the VMDK, a Filesystem in it, and you want to extract the files in the Filesystem?

**Comment by masahiro331** [comment]
@stream1990 
What does it mean?
Is there a partition layer such as MasterBootRecord in the VMDK, a Filesystem in it, and you want to extract the files in the Filesystem?
